import {
    Xls,
    Jpg,
    Jpeg,
    Doc,
    Docx,
    CameraPhoto,
    Pdf,
    Archive,
    Document,
    Music1,
    Music2,
    Movie,
    Settings,
    DocEdit,
    DocPreview,
} from '@fcc/icons';

const EXTENSION_ICONS = {
    xls: Xls,
    xlsx: Xls,
    jpg: Jpg,
    jpeg: Jpeg,
    jpegx: CameraPhoto,
    png: CameraPhoto,
    doc: Doc,
    docx: Docx,
    pdf: Pdf,
    zip: Archive,
    rar: Archive,
    rar5: Archive,
    '7z': Archive,
    tar: Archive,
    gz: Archive,
    mp3: Music1,
    wma: Music1,
    wav: Music1,
    flac: Music1,
    midi: Music2,
    ogg: Music2,
    avi: Movie,
    mov: Movie,
    divx: Movie,
    mp4: Movie,
    mpg: Movie,
    wmv: Movie,
    txt: DocEdit,
    dll: Settings,
    deb: Settings,
    dev: Settings,
    ppt: DocPreview,
    pptx: DocPreview,
};

export const getIconByExtension = (extension: string) => {
    return EXTENSION_ICONS[extension.toLowerCase()] ?? Document;
};
