export const LogoTypes = {
    blackHorizontalOneLineEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-horizontal-one-line-en.svg',
    blackHorizontalOneLineRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-horizontal-one-line-ru.svg',
    blackHorizontalTwoLinesEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-horizontal-two-lines-en.svg',
    blackHorizontalTwoLinesRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-horizontal-two-lines-ru.svg',
    blackVerticalOneLineEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-vertical-one-line-en.svg',
    blackVerticalOneLineRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-vertical-one-line-ru.svg',
    blackVerticalTwoLinesEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-vertical-two-lines-en.svg',
    blackVerticalTwoLinesRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/black-vertical-two-lines-ru.svg',
    logoWithBg: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/logo-with-bg.svg',
    logo: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/logo.svg',
    originalHorizontalOneLineEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-horizontal-one-line-en.svg',
    originalHorizontalOneLineRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-horizontal-one-line-ru.svg',
    originalHorizontalTwoLinesEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-horizontal-two-lines-en.svg',
    originalHorizontalTwoLinesRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-horizontal-two-lines-ru.svg',
    originalVerticalOneLineEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-vertical-one-line-en.svg',
    originalVerticalOneLineRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-vertical-one-line-ru.svg',
    originalVerticalTwoLinesEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-vertical-two-lines-en.svg',
    originalVerticalTwoLinesRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/original-vertical-two-lines-ru.svg',
    whiteHorizontalOneLineEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-horizontal-one-line-en.svg',
    whiteHorizontalOneLineRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-horizontal-one-line-ru.svg',
    whiteHorizontalTwoLinesEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-horizontal-two-lines-en.svg',
    whiteHorizontalTwoLinesRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-horizontal-two-lines-ru.svg',
    whiteVerticalOneLineEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-vertical-one-line-en.svg',
    whiteVerticalOneLineRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-vertical-one-line-ru.svg',
    whiteVerticalTwoLinesEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-vertical-two-lines-en.svg',
    whiteVerticalTwoLinesRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/white-vertical-two-lines-ru.svg',
    digitalWhiteHorizontalOneLineEn:
        'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-horizontal-one-line-en.svg',
    digitalWhiteHorizontalOneLineRu:
        'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-horizontal-one-line-ru.svg',
    digitalWhiteHorizontalTwoLinesEn:
        'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-horizontal-two-lines-en.svg',
    digitalWhiteHorizontalTwoLinesRu:
        'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-horizontal-two-lines-ru.svg',
    digitalWhiteVerticalOneLineEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-vertical-one-line-en.svg',
    digitalWhiteVerticalOneLineRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-vertical-one-line-ru.svg',
    digitalWhiteVerticalTwoLinesEn: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-vertical-two-lines-en.svg',
    digitalWhiteVerticalTwoLinesRu: 'https://cdn-rf.raiffeisen.ru/ds/img/logo/digital-white-vertical-two-lines-ru.svg',
};
