/* eslint-disable */
interface Person {
    id: number | string;
    level: string;
    firstName: string;
    lastName: string;
    position: string;
    phone: string;
}

export const fullData: Person[] = [
    {
        id: '0',
        level: '1',
        firstName: 'Joseph',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '1',
        level: '2',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '2',
        level: '3',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '3',
        level: '3',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'PM',
        phone: '916456789',
    },
    {
        id: '4',
        level: '1',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '5',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '6',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '7',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '8',
        level: '1',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '9',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '10',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '11',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '12',
        level: '1',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '13',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '14',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '15',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '16',
        level: '1',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '17',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '18',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '19',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '20',
        level: '1',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '21',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '22',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '23',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '24',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '25',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '26',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '27',
        level: '1',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '28',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '29',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '30',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '31',
        level: '1',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        phone: '9163456789',
    },
    {
        id: '32',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '33',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '34',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '35',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '36',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '37',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
    {
        id: '38',
        level: '1',
        firstName: 'James',
        lastName: 'Jameson',
        position: 'CTO',
        phone: '916456789',
    },
    {
        id: '39',
        level: '1',
        firstName: 'Jane',
        lastName: 'Doe',
        position: 'PM',
        phone: '9163456780',
    },
    {
        id: '49',
        level: '1',
        firstName: 'Johnnie',
        lastName: 'Walker',
        position: 'Software Engineer',
        phone: 'none',
    },
];

export const data: Person[] = fullData.slice(0, 5);

export let currentPage = 1;
